
# 配置api端口
# tomcat的URI编码
server:
  tomcat:
    uri-encoding: UTF-8
  port: 8080
# mybatis配置
mybatis:
  type-aliases-package: com.aiolos.pojo
  mapper-locations: classpath:mapper/*.xml
# 通用mapper配置
mapper:
  mappers: com.aiolos.utils.MyMapper
  not-empty: false
  identity: MYSQL
# 分页插件
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true
  params: count=countSql
# 配置数据源相关 使用HikariCP数据源
# jdbc_config datasource
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/chat?useUnicode=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: aiolos1204285
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 600000
      pool-name: DatebookHikariCP
      max-lifetime: 28740000
      connection-test-query: SELECT 1